### ISSUE TITLE
[1.19.2] [Forge] [Request] Loading custom Condensed Entries from datapacks

### ISSUE THREAD

**Issue by ildiem** [wisp-forest/CondensedCreativeItems#8]
Based on the wiki, it seems the mod currently supports loading condensed entries in datapack format, but not _from_ a datapack. I tried copying and pasting the examples from the wiki into a properly structured datapack just to make sure, and it didn't load.

Personally I would find it really useful to be able to load condensed entries from datapacks, just because of how my workflow is structured. Is this possible?

**Comment by Dragon-Seeker** [comment]
Should have phrased such as ResourcePack and not datapack. It is a client-side-only mod meaning that it's loaded thru a resource pack instead due to such.

Edit: I don't see any reason to support datapack format due to this being a primarily clientside mod and only cosmetically effects the creative tab.

**Comment by ildiem** [comment]
Ohh okay thanks!

Just to clarify, I can load in my own condensed entries from a resource pack with the mod as it is right now? Under `assets/<mod id>/condensed_entries`?

**Comment by Dragon-Seeker** [comment]
Yep
